"use strict";
import { auth, db } from "../js/firebase-config.js";
import { collection, getDocs } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const API="https://juniorgame-stripe.onrender.com", nf=new Intl.NumberFormat("es-MX"), df=new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"});
const $=id=>document.getElementById(id), safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])), num=v=>Number.isFinite(Number(v))?Number(v):0;
let users=[],audit=[];
const name=d=>d.nombre||d.customName||d.name||d.displayName||"Usuario sin nombre", email=d=>d.email||"Sin correo", jf=d=>d.playerId||d.jfId||d.JF_ID||d["JF-ID"]||d.shortId||"Sin ID JF";
const date=v=>{try{const x=v?.toDate?v.toDate():v?new Date(v):null;return x&&!isNaN(x)?x:null}catch{return null}};
function status(d){const until=date(d.suspendedUntil);if(d.banned||d.disabled)return "banned";if(d.suspended&&(!until||until>new Date()))return "suspended";return "active"}
function countTrue(o){return o&&typeof o==="object"?Object.values(o).filter(Boolean).length:0}
async function loadUsers(force=false){if(users.length&&!force)return users;const s=await getDocs(collection(db,"users"));users=s.docs.map(x=>({uid:x.id,data:x.data()}));renderAll();return users}
async function api(path){const u=auth.currentUser;if(!u)throw Error("La sesión administrativa expiró.");const r=await fetch(API+path,{headers:{Authorization:`Bearer ${await u.getIdToken(true)}`}}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.error||"No se pudo consultar el backend.");return p}
function renderPlayers(){const q=($("gmsPlayerSearch")?.value||"").trim().toLowerCase(),filter=$("gmsPlayerState")?.value||"all";const active=users.filter(x=>status(x.data)==="active").length,suspended=users.filter(x=>status(x.data)==="suspended").length,banned=users.filter(x=>status(x.data)==="banned").length,incomplete=users.filter(x=>!x.data.email||name(x.data)==="Usuario sin nombre"||jf(x.data)==="Sin ID JF").length;$("gmsActivePlayers").textContent=nf.format(active);$("gmsSuspendedPlayers").textContent=nf.format(suspended);$("gmsBannedPlayers").textContent=nf.format(banned);$("gmsIncompletePlayers").textContent=nf.format(incomplete);const f=users.filter(x=>(filter==="all"||status(x.data)===filter)&&(!q||[x.uid,name(x.data),email(x.data),jf(x.data)].some(v=>String(v).toLowerCase().includes(q)))).slice(0,100);$("gmsPlayerDirectory").innerHTML=f.length?`<table class="gms-table"><thead><tr><th>Jugador</th><th>ID JF</th><th>Estado</th><th>Nivel</th><th>Monedas</th><th>Diamantes</th><th></th></tr></thead><tbody>${f.map(x=>{const d=x.data,st=status(d);return `<tr><td><div class="gms-user-cell"><span class="gms-avatar">${safe(name(d).slice(0,1).toUpperCase())}</span><div><strong>${safe(name(d))}</strong><small>${safe(email(d))}</small></div></div></td><td>${safe(jf(d))}</td><td><span class="gms-status ${st}">${st==="active"?"Activa":st==="suspended"?"Suspendida":"Baneada"}</span></td><td>${nf.format(num(d.nivelActual??d.level??d.progreso?.nivelActual))}</td><td>${nf.format(num(d.coins??d.monedas))}</td><td>${nf.format(num(d.diamonds??d.diamantes))}</td><td><button class="gms-open-account" data-account-search="${safe(jf(d)!=="Sin ID JF"?jf(d):email(d))}" type="button">Gestionar</button></td></tr>`}).join("")}</tbody></table>`:'<div class="gms-empty">No hay jugadores que coincidan.</div>';document.querySelectorAll("[data-account-search]").forEach(b=>b.addEventListener("click",()=>{document.querySelector('[data-view="cuentas"]')?.click();setTimeout(()=>{const i=$("accountSearch");if(i){i.value=b.dataset.accountSearch;i.dispatchEvent(new Event("input"))}},150)}))}
function tally(values){const m=new Map();values.filter(Boolean).forEach(v=>m.set(String(v),1+(m.get(String(v))||0)));return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function renderInventory(){let items=0,pets=0,races=0,equipped=0,withItems=0,withPets=0,withRaces=0;const eq=[];users.forEach(({data:d})=>{const a=countTrue(d.inventarioArticulos),p=countTrue(d.perritosJrComprados),r=countTrue(d.razasCompradas);items+=a;pets+=p;races+=r;if(a)withItems++;if(p)withPets++;if(r)withRaces++;const vals=[d.skinEquipada,d.perritoEquipado||d.mascotaEquipada,d.razaEquipada].filter(Boolean);if(vals.length){equipped++;eq.push(...vals)}});$("gmsTotalItems").textContent=nf.format(items);$("gmsTotalPets").textContent=nf.format(pets);$("gmsTotalRaces").textContent=nf.format(races);$("gmsEquippedPlayers").textContent=nf.format(equipped);const top=tally(eq).slice(0,10);$("gmsPopularEquipment").innerHTML=top.length?top.map(([k,v],i)=>`<div class="data-row"><div><strong>#${i+1} ${safe(k)}</strong><span>Equipado actualmente</span></div><div class="value">${nf.format(v)} jugadores</div></div>`).join(""):'<div class="empty-inline">Aún no hay equipamiento registrado.</div>';const total=users.length||1;$("gmsInventoryCoverage").innerHTML=[["Con artículos",withItems],["Con Perritos Jr.",withPets],["Con razas",withRaces],["Con algo equipado",equipped]].map(([l,v])=>{const p=Math.round(v/total*100);return `<div class="bar-item"><header><span>${l}</span><b>${v} · ${p}%</b></header><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div></div>`}).join("")}
function renderModeration(){const cases=users.filter(x=>{const d=x.data;return status(d)!=="active"||d.chatMuted||d.mutedUntil||d.eventsBlocked||num(d.adminWarnings)>0});const banned=users.filter(x=>status(x.data)==="banned").length,suspended=users.filter(x=>status(x.data)==="suspended").length,muted=users.filter(x=>x.data.chatMuted||(date(x.data.mutedUntil)&&date(x.data.mutedUntil)>new Date())).length,events=users.filter(x=>x.data.eventsBlocked).length;$("gmsModBanned").textContent=banned;$("gmsModSuspended").textContent=suspended;$("gmsModMuted").textContent=muted;$("gmsModEvents").textContent=events;$("gmsModerationCases").innerHTML=cases.length?cases.map(x=>{const d=x.data,t=[];if(status(d)==="banned")t.push("Baneo");if(status(d)==="suspended")t.push("Suspensión");if(d.chatMuted||d.mutedUntil)t.push("Chat silenciado");if(d.eventsBlocked)t.push("Eventos bloqueados");if(num(d.adminWarnings))t.push(`${num(d.adminWarnings)} advertencias`);return `<div class="data-row gms-case"><div><strong>${safe(name(d))}</strong><span>${safe(email(d))}</span><div class="gms-case-tags">${t.map(a=>`<span class="gms-tag">${safe(a)}</span>`).join("")}</div></div><div class="value">${safe(jf(d))}</div></div>`}).join(""):'<div class="empty-inline">No hay medidas activas.</div>'}
function drafts(){try{return JSON.parse(localStorage.getItem("jg.gms.events")||"[]")}catch{return[]}}
function renderEvents(){const a=drafts();$("gmsEventDrafts").innerHTML=a.length?a.map((x,i)=>`<div class="data-row"><div><strong>${safe(x.name)}</strong><span>${safe(x.type)} · ${safe(x.reward||"Sin recompensa")}</span><small>${x.start?safe(df.format(new Date(x.start))):"Sin fecha"}</small></div><button class="gms-event-delete" data-event-delete="${i}" type="button">×</button></div>`).join(""):'<div class="empty-inline">No hay eventos preparados.</div>';document.querySelectorAll("[data-event-delete]").forEach(b=>b.addEventListener("click",()=>{const a=drafts();a.splice(Number(b.dataset.eventDelete),1);localStorage.setItem("jg.gms.events",JSON.stringify(a));renderEvents()}))}
async function loadAudit(){try{const p=await api("/admin/audit");audit=Array.isArray(p.items)?p.items:[];renderAudit()}catch(e){$("gmsAuditList").innerHTML=`<div class="empty-inline">${safe(e.message)}</div>`}}
function renderAudit(){const q=($("gmsAuditSearch")?.value||"").toLowerCase(),filt=$("gmsAuditFilter")?.value||"all";const a=audit.filter(x=>(filt==="all"||x.action===filt||(filt==="moderation"&&!['adjustBalance','inventory'].includes(x.action)))&&(!q||[x.actionLabel,x.targetName,x.targetUid,x.reason,x.adminEmail].some(v=>String(v||"").toLowerCase().includes(q))));$("gmsAuditList").innerHTML=a.length?a.map(x=>`<div class="data-row"><div><strong>${safe(x.actionLabel||x.action)}</strong><span>${safe(x.targetName||x.targetUid)} · ${safe(x.reason||"Sin motivo")}</span><small>${safe(x.adminEmail||x.adminUid||"")}</small></div><div class="value">${x.createdAt?safe(df.format(new Date(x.createdAt))):"Pendiente"}</div></div>`).join(""):'<div class="empty-inline">No hay acciones para este filtro.</div>'}
function renderAll(){renderPlayers();renderInventory();renderModeration();renderEvents()}
$("gmsPlayerSearch")?.addEventListener("input",renderPlayers);$("gmsPlayerState")?.addEventListener("change",renderPlayers);$("gmsRefreshPlayers")?.addEventListener("click",()=>loadUsers(true));$("gmsSaveEvent")?.addEventListener("click",()=>{const name=$("gmsEventName").value.trim();if(!name){$("gmsEventName").focus();return}const a=drafts();a.unshift({name,type:$("gmsEventType").value,reward:$("gmsEventReward").value.trim(),start:$("gmsEventStart").value,notes:$("gmsEventNotes").value.trim(),createdAt:Date.now()});localStorage.setItem("jg.gms.events",JSON.stringify(a.slice(0,50)));["gmsEventName","gmsEventReward","gmsEventStart","gmsEventNotes"].forEach(id=>$(id).value="");renderEvents()});$("gmsRefreshAudit")?.addEventListener("click",loadAudit);$("gmsAuditSearch")?.addEventListener("input",renderAudit);$("gmsAuditFilter")?.addEventListener("change",renderAudit);
window.addEventListener("juniorgame:admin-ready",()=>loadUsers().catch(console.error),{once:true});window.addEventListener("juniorgame:view-change",e=>{if(["jugadores","inventario","moderacion"].includes(e.detail?.view))loadUsers().catch(console.error);if(e.detail?.view==="auditoria")loadAudit()});
